version: '3.7'
services:
    flask:
      build: ./
      dockerfile: Dockerfile
      container_name: flask
      volumes:
        - ./src:/src/
        - ../log/flask/: /src/log
        - PYTHONUNBUFFERED=1  # display print()
        - FLASK_APP=/src/main.py
        - FLASK_SECRET_KEY='top_secret_key'
        - DEBUG=1
      command: flask run --host=0.0.0.0
